name: SetSpeed
main: net.D3GN.MiracleM4n.SetSpeed.SetSpeed
version: 1.5.5
website: 
author: MiracleM4n
description: Set Your Speed :O
commands:
    setspeed:
        description: Set Speed
        usage: |
            /<command> [radius]
            Example: /<command> View This
            Example: /<command> 10 - sets your speed to 10x normal.
        description: Set Speed
    speedoff: 
        description: Turn Speed Off
        usage: |
            /<command>
    speedon:
        description: Turn Speed On
        usage: |
            /<command>
            